import React from 'react';
import { FileText, Download, Clock, Plus, BarChart, ShieldCheck, UserX, Loader2 } from 'lucide-react';
import { MOCK_REPORTS } from '../constants';

const ReportsView: React.FC = () => {
  const templates = [
    { title: 'Executive Security Summary', description: 'High-level overview of risk posture, anomalies, and ROI metrics.', icon: BarChart, color: 'bg-indigo-500' },
    { title: 'PCI-DSS Compliance Audit', description: 'Detailed logs and access reviews for CDE environment scope.', icon: ShieldCheck, color: 'bg-emerald-500' },
    { title: 'High Risk User Activity', description: 'Deep dive into users with risk scores > 80 over the last 30 days.', icon: UserX, color: 'bg-red-500' },
  ];

  return (
    <div className="p-8 space-y-8 animate-fade-in bg-[#0f172a] min-h-screen">
      
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-white">Reports & Compliance</h1>
          <p className="text-slate-400 mt-1">Generate audits, export logs, and schedule automated summaries.</p>
        </div>
        <button className="bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 shadow-lg shadow-indigo-900/50 transition-colors">
          <Plus className="w-4 h-4" />
          Create Custom Report
        </button>
      </div>

      {/* Templates */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {templates.map((template, idx) => (
          <div key={idx} className="bg-slate-900 border border-slate-800 p-6 rounded-xl hover:border-slate-700 transition-all group cursor-pointer">
            <div className={`w-12 h-12 rounded-lg ${template.color} flex items-center justify-center mb-4 shadow-lg opacity-90 group-hover:opacity-100 group-hover:scale-105 transition-all`}>
              <template.icon className="w-6 h-6 text-white" />
            </div>
            <h3 className="text-lg font-bold text-white mb-2">{template.title}</h3>
            <p className="text-sm text-slate-400 mb-6">{template.description}</p>
            <button className="text-sm font-medium text-indigo-400 hover:text-indigo-300 flex items-center gap-1">
              Generate Now &rarr;
            </button>
          </div>
        ))}
      </div>

      {/* Recent Reports Table */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
        <div className="p-6 border-b border-slate-800 flex justify-between items-center">
          <h3 className="text-lg font-bold text-white">Report Archive</h3>
          <div className="flex gap-2">
            <select className="bg-slate-800 border border-slate-700 text-slate-300 text-sm rounded-lg px-3 py-1.5 outline-none">
              <option>All Types</option>
              <option>Executive</option>
              <option>Compliance</option>
            </select>
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="bg-slate-800/50 text-slate-400 text-xs uppercase tracking-wider">
                <th className="p-4 font-medium">Report Name</th>
                <th className="p-4 font-medium">Type</th>
                <th className="p-4 font-medium">Generated By</th>
                <th className="p-4 font-medium">Date</th>
                <th className="p-4 font-medium">Size</th>
                <th className="p-4 font-medium">Status</th>
                <th className="p-4 font-medium text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800">
              {MOCK_REPORTS.map((report) => (
                <tr key={report.id} className="hover:bg-slate-800/30 transition-colors">
                  <td className="p-4">
                    <div className="flex items-center gap-3">
                      <FileText className="w-5 h-5 text-slate-500" />
                      <span className="text-slate-200 font-medium">{report.name}</span>
                    </div>
                  </td>
                  <td className="p-4">
                    <span className="text-xs bg-slate-800 text-slate-300 px-2 py-1 rounded border border-slate-700">
                      {report.type.replace('_', ' ')}
                    </span>
                  </td>
                  <td className="p-4 text-slate-400 text-sm">{report.generatedBy}</td>
                  <td className="p-4 text-slate-400 text-sm">{new Date(report.generatedAt).toLocaleDateString()}</td>
                  <td className="p-4 text-slate-400 text-sm font-mono">{report.size}</td>
                  <td className="p-4">
                    {report.status === 'READY' ? (
                      <span className="flex items-center gap-1.5 text-xs font-medium text-emerald-500 bg-emerald-500/10 px-2 py-1 rounded">
                        <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span> Ready
                      </span>
                    ) : (
                      <span className="flex items-center gap-1.5 text-xs font-medium text-orange-500 bg-orange-500/10 px-2 py-1 rounded">
                        <Loader2 className="w-3 h-3 animate-spin" /> Generating
                      </span>
                    )}
                  </td>
                  <td className="p-4 text-right">
                    <button 
                      className="p-2 hover:bg-slate-700 rounded text-slate-400 hover:text-white disabled:opacity-50"
                      disabled={report.status !== 'READY'}
                    >
                      <Download className="w-4 h-4" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ReportsView;